# Generated by Django 3.0.5 on 2020-04-12 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='completed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
